In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

ModuleNotFoundError: No module named 'pandas'

In [ ]:
df=pd.read_csv('/spam_or_not_spam.csv')
df

                                                  email  label
0      date wed NUMBER aug NUMBER NUMBER NUMBER NUMB...      0
1     martin a posted tassos papadopoulos the greek ...      0
2     man threatens explosion in moscow thursday aug...      0
3     klez the virus that won t die already the most...      0
4      in adding cream to spaghetti carbonara which ...      0
...                                                 ...    ...
2995   abc s good morning america ranks it the NUMBE...      1
2996   hyperlink hyperlink hyperlink let mortgage le...      1
2997   thank you for shopping with us gifts for all ...      1
2998   the famous ebay marketing e course learn to s...      1
2999   hello this is chinese traditional 子 件 NUMBER世...      1

[3000 rows x 2 columns]

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [ ]:
df.tail()

                                                  email  label
2995   abc s good morning america ranks it the NUMBE...      1
2996   hyperlink hyperlink hyperlink let mortgage le...      1
2997   thank you for shopping with us gifts for all ...      1
2998   the famous ebay marketing e course learn to s...      1
2999   hello this is chinese traditional 子 件 NUMBER世...      1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   email   2999 non-null   object
 1   label   3000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 47.0+ KB

In [ ]:
df.isnull().sum()

email    1
label    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(127)

In [ ]:
df.duplicated().sum()

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
email,2872,2872,hello this is chinese traditional 子 件 NUMBER世...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
label,2872.0,NaN,NaN,NaN,0.148677,0.355832,0.0,0.0,0.0,0.0,1.0

In [ ]:
df.shape

(2872, 2)

In [ ]:
df['label']=df['label'].map({1:'spam',0:'not spam'})

In [ ]:
df['label'].value_counts()

label
not spam    2445
spam         427
Name: count, dtype: int64

In [ ]:
df.describe(include='all').T

      count unique                                                top  freq
email  2872   2872   hello this is chinese traditional 子 件 NUMBER世...     1
label  2872      2                                           not spam  2445

In [ ]:
df.columns

Index(['email', 'label'], dtype='object')

In [ ]:
for i in df.columns:
  if(df[i].dtype!='object'):
   plt.boxplot(df[i])
   plt.xlabel(i)
   plt.title(i,"box plot")
   plt.show()

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['label']=le.fit_transform(df['label'])

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
corpus=df['email']
x=vectorizer.fit_transform(corpus)

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.04638347]])

In [ ]:
df

                                                  email     label
0      date wed NUMBER aug NUMBER NUMBER NUMBER NUMB...  not spam
1     martin a posted tassos papadopoulos the greek ...  not spam
2     man threatens explosion in moscow thursday aug...  not spam
3     klez the virus that won t die already the most...  not spam
4      in adding cream to spaghetti carbonara which ...  not spam
...                                                 ...       ...
2995   abc s good morning america ranks it the NUMBE...      spam
2996   hyperlink hyperlink hyperlink let mortgage le...      spam
2997   thank you for shopping with us gifts for all ...      spam
2998   the famous ebay marketing e course learn to s...      spam
2999   hello this is chinese traditional 子 件 NUMBER世...      spam

[2872 rows x 2 columns]

In [ ]:
y=df['label']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(max_iter=1000)
lr.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [ ]:
y_pred=lr.predict(x_test)
y_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1])

In [ ]:
y_test

732     0
2955    1
1293    0
1743    0
941     0
       ..
1892    0
163     0
1921    0
252     0
2567    1
Name: label, Length: 575, dtype: int64

In [ ]:
from sklearn.metrics import *
accuracy_score(y_pred,y_test)*100

95.65217391304348

In [ ]:
new_email = ["get a kick out of our huge annuity bonuses earn a NUMBER NUMBER cash bonus for every NUMBER annuity applications with any of our four top carriers by NUMBER NUMBER NUMBER deadline too soon no problem earn an NUMBER cash bonus for every NUMBER annuity applications with any of our four top carriers by NUMBER NUMBER NUMBER get your bonus call m o marketing today NUMBER NUMBER NUMBER or please fill out the form below for more information name e mail phone city state bonuses awarded from m o marketing on paid issued business for agent use only offer subject to change without notice offer starts NUMBER NUMBER NUMBER offer ends NUMBER NUMBER NUMBER offer good in all states except wi in de not available with all carriers we don t want anyone to receive our mailings who does not wish to receive them this is a professional communication sent to insurance professionals to be removed from this mailing list do not reply to this message instead go here URL URL legal notice URL "]
new_email_vec = vectorizer.transform(new_email)
prediction = lr.predict(new_email_vec)
probability = lr.predict_proba(new_email_vec)
if prediction[0] == 1:
    print("Spam")
else:
    print("Not Spam")

Spam

In [ ]:
!git --version

git version 2.34.1

In [ ]:
!git config --global user.name
"ashutoshkarspacex-cmd"
!git config --global user.email "ashutoshkarspacex@gmail.com"

In [ ]:
!git clone https://github.com/ashutoshkarspacex-cmd/Machine-learning-project-.git

Cloning into 'Machine-learning-project-'...

In [ ]:
/Machine-learning-project-.git

SyntaxError: invalid syntax (405502147.py, line 1)